name: Docker
on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: token
        with:
          app_id: ${{secrets.APP_ID}}
          private_key: ${{secrets.APP_PRIVKEY}}
      
      - uses: actions/checkout@v2
      
      - name: Build and Push Docker Image
        run: |
          image="ghcr.io/msrd0/element"
          docker pull "$image:cache" || true
          docker build . \
            --pull \
            --target builder \
            --cache-from "$image:cache" \
            --tag "$image:cache"
          docker build . \
            --pull \
            --cache-from "$image:cache" \
            --tag "$image"
          version="$(docker run --rm "$image" /bin/element version)"
          docker tag "$image" "$image:$version"
          
          docker login -u msrd0 -p "${{steps.token.outputs.token}}" ghcr.io
          docker push "$image:cache"
          docker push "$image:$version"
          docker push "$image"
